domain: beyondbordergroup.com
languages:
  - en
  - fr

targets:
  primary_market: Global (English)
  secondary_markets:
    - France
    - Belgium

competitors:
  - wpic.co
  - genuine-asia.com
  - ecommercetochina.com
  - web2asia.com
  - azoyagroup.com
  - agencychina.com
  - daxueconsulting.com
  - marketingtochina.com
  - ecommercechinaagency.com
  - tmogroup.asia
  - eggsist.com
